server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.1.138
    port: 5672
    username: admin
    password: rabbitmq
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost

    #先从总体的情况分析，推送消息存在四种情况：
    #①消息推送到server，但是在server里找不到交换机
    #②消息推送到server，找到交换机了，但是没找到队列
    #③消息推送到sever，交换机和队列啥都没找到
    #④消息推送成功
    #确认消息已经发送到交换机（Exchange)|以下两个选项如果未开启 则RabbitConfig即使注入框架也不生效
    publisher-confirm-type: correlated
    #确认消息已发送到队列
    publisher-returns: true